project 1 foodapp/mysite/food/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name = 'food'

urlpatterns = [
    path('', views.IndexClassView.as_view(), name = 'index'),
    path('<int:pk>/', views.FoodDetail.as_view(), name ='detail'),
    path('add/', views.CreateItem.as_view(), name='create_item'),
    path('update/<int:item_id>/', views.update_item, name='update_item'),
    path('delete/<int:item_id>/', views.delete_item, name='delete_item'),

]

project 1 foodapp/mysite/food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
# Create your models here.
class Item(models.Model):
    
    def __str__(self) -> str:
        return self.item_name
    
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    item_name = models.CharField(max_length=200)
    item_desc = models.CharField(max_length=200)
    item_price = models.IntegerField()
    item_image = models.CharField(max_length=500,
                                  default='https://cdn-icons-png.flaticon.com/512/1377/1377194.png')
    
    def get_absolute_url(self):
        return reverse('food:detail', kwargs={'pk':self.pk})

project 1 foodapp/mysite/food/forms.py
from django import forms
from .models import Item

class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['item_name', 'item_desc', 'item_price', 'item_image']

project 1 foodapp/mysite/food/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Item
from django.template import loader
from .forms import ItemForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
# Create your views here.

# def index(request):
#     item_list = Item.objects.all()
#     context = {
#         'item_list': item_list,
#     }
#     return render(request, 'food/index.html', context)

class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


# def detail(request, item_id):
#     item = Item.objects.get(pk = item_id)
#     context = {
#         'item': item
#     }
#     return render(request, 'food/detail.html', context)


class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'
    
    
# def create_item(request):
#     form = ItemForm(request.POST or None)
    
#     if form.is_valid():
#         form.save()
#         return redirect('food:index')
#     context = {'form':form}
#     return render(request, 'food/item-form.html', context)

class CreateItem(CreateView):
     model = Item
     fields = ['item_name', 'item_desc', 'item_price', 'item_image']
     template_name = 'food/item-form.html'
     
     def form_valid(self, form):
         form.instance.user_name = self.request.user
         return super().form_valid(form)

def update_item(request, item_id):
    item = Item.objects.get(id = item_id)
    form = ItemForm(request.POST or None, instance= item)
    
    if form.is_valid():
        form.save()
        return redirect('food:index')
    
    context = {'form':form, 'item':item}
    return render(request, 'food/item-form.html', context)

def delete_item(request, item_id):
    item = Item.objects.get(id = item_id)
    
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    
    
    context = {'item':item}
    return render(request, 'food/item-delete.html', context)


project 1 foodapp/mysite/food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <title>Document</title>
</head>

<body>
    <nav class='navbar navbar-dark bg-danger'>
        <a href='#' class='navbar-brand'>FoodApp</a>

        <div class='navbar'>
            
            <a class='nav-item nav-link' href="{% url 'food:create_item'%}"> Add item</a>
            <a class='nav-item nav-link' href='#'> Delete item</a>
            <a class='nav-item nav-link' href='#'> View item</a>
            {%if user.is_authenticated%}
            <a href="{%url 'logout'%}">Logout</a>
            <a href="{%url 'profile'%}">Profile</a>
            {%else%}
            <a href="{%url 'login'%}">Login</a>
            {%endif%}
        </div>
    </nav>

    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}">
        {{message}}

    </div>



    {% endfor %}
    {% endif %}

    {% block body %}
    {% endblock %}

</body>

</html>

project 1 foodapp/mysite/food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{item.item_image}}" class="img-fluid" />
        </div>


        <div class="col-md-6">
            <h1>{{object.item_name}}</h1>
            <h2>$ {{object.item_price}}</h2>
            <h3>{{object.item_desc}}</h3>
            <h3>{{object.user_name}}</h3>
            <a href="{% url 'food:delete_item' item.id %}">Delete</a>
        </div>
    </div>



</div>


{% endblock %}

project 1 foodapp/mysite/food/templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    {% block body %}
    {% for item in item_list %}

    <div class="row">

        <div class="col-md-3 offset-md-2">
            <img class ="img-fluid" src="{{ item.item_image }}" alt="Responsive image"/>
        </div>
        
        <div class="col-md-4">
            <h3>{{ item.item_name}}</h3>
            <h5>{{ item.item_desc}}</h5>
            <h6>$ {{ item.item_price}}</h6>
            <h6> {{ item.user_name}}</h6>
            </div>
            
        <div class="col-md-2">
            <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
        </div>
    </div>


    {% endfor %}
    {% endblock %}
</body>

</html>

project 1 foodapp/mysite/food/templates/food/item-delete.html
<form method="POST">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{item.item_name}}</h2>

    <button type="submit">Confirm</button>
</form>

project 1 foodapp/mysite/food/templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
<form method="POST">
    {% csrf_token %}
    {{form}}
    <button type="submit">Save</button>


</form>
{% endblock %}